#!/usr/bin/env bash
###############################################################################
# 1-install_nginx_web_server.sh
#
# Description: This Bash script installs the Nginx web server on an Ubuntu
# server and verifies its installation by checking if it serves a page with
# the string "Hello World!" when queried.
#
# Author: Alexander Udeogaranya
# GitHub: 
#  - https://github.com/Dr-dyrane/alx-system_engineering-devops/0x0C-web_server
#
# Usage: ./1-install_nginx_web_server.sh
#
# Requirements:
#   - The script should be run on an Ubuntu server.
#   - Nginx should be listening on port 80.
#   - When querying Nginx at its root / with a GET request using curl, it must
#     return a page that contains the string "Hello World!"
#   - The script cannot use systemctl for restarting nginx.
#
# Example:
#   $ ./1-install_nginx_web_server.sh
#
# The script will install Nginx, configure it as required, and perform the
# verification steps.
###############################################################################

# Update the package list and install Nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Create a default index.html file with "Hello World!" message
echo "Hello World!" | sudo tee /var/www/html/index.html

# Start Nginx without using systemctl
sudo /etc/init.d/nginx start
