#!/usr/bin/env bash
###############################################################################
# 3-redirection.sh
#
# Description: This Bash script configures Nginx to perform a 301 Moved
# Permanently redirection from /redirect_me to another specified page. It also
# installs Nginx and sets up a basic configuration.
#
# Author: Alexander Udeogaranya
# GitHub: 
#  - https://github.com/Dr-dyrane/alx-system_engineering-devops/0x0C-web_server
#
# Usage: ./3-redirection.sh REDIRECT_PAGE
#
# Requirements:
#   - REDIRECT_PAGE: The URL to which /redirect_me should be redirected.
#   - The script should be run on a machine with Nginx not installed.
#
# Example:
#   $ ./3-redirection.sh https://www.youtube.com/watch?v=QH2-TGUlwu4
#
# The script will configure Nginx for the specified redirection.
###############################################################################

# Update the package list
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create a directory and an index.html file
sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
echo "Hello World!" | sudo tee /etc/nginx/html/index.html

# Configure Nginx redirection
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Restart Nginx service
sudo service nginx restart
