#!/usr/bin/env bash
###############################################################################
# 4-not_found_page_404.sh
#
# Description: This Bash script configures Nginx to have a custom 404 page
# that returns an HTTP 404 error code and contains the string "Ceci n'est
# pas une page."
#
# Author: Alexander Udeogaranya
# GitHub: 
#  - https://github.com/Dr-dyrane/alx-system_engineering-devops/0x0C-web_server
#
# Usage: ./4-not_found_page_404.sh
#
# Requirements:
#   - The script should be run on a machine with Nginx installed.
#
# Example:
#   $ ./4-not_found_page_404.sh
#
# The script will configure Nginx for the custom 404 page.
###############################################################################

# Create a custom 404 error page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404_custom.html

# Create an Nginx configuration file for the custom 404 page
cat > /etc/nginx/sites-available/custom_404 <<EOF
server {
    listen 80 default_server;
    server_name _;

    error_page 404 /404_custom.html;
    location = /404_custom.html {
        root /usr/share/nginx/html;
    }
}
EOF

# Remove the default Nginx configuration
rm /etc/nginx/sites-enabled/default

# Enable the custom 404 configuration
ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Reload Nginx to apply the new configuration
service nginx reload

echo "Nginx configured for custom 404 page."
