#!/usr/bin/env bash
###############################################################################
# This Bash script configures Nginx to include a custom HTTP response header.
# It ensures that the HTTP response contains the custom header on web-01 and web-02 servers.
#
# Requirements:
# - Configure Nginx with a custom HTTP header named X-Served-By.
# - The value of the custom HTTP header must be the hostname of the server Nginx is running on.
#
# Usage:
# - Run this script on a brand new Ubuntu machine to meet the task requirements.
#
# Note:
# - This script assumes that you have sudo privileges to install packages and modify Nginx configuration.
#
# Example Usage:
# $ ./0-custom_http_response_header
###############################################################################


# Get the hostname of the server
var=$(hostname)

# Nginx configuration strings
new_string="error_page 404 \/custom_404.html;\n location \/redirect_me {\n return 301 \$scheme:\/\/www.google.com;"
new_string2="server {\n\tadd_header X-Served-By $var;"

# Update the package list and install Nginx
apt-get update -y
apt-get install nginx -y

# Create a basic index.html file
echo "Hello World!" > /usr/share/nginx/html/index.html

# Create a directory for custom error page
mkdir -p /var/www/html

# Create a custom 404 error page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Modify the Nginx configuration file to include custom error handling and the custom header
sudo sed -i -E "s/^[^#]+location \/ \{/$new_string/" /etc/nginx/sites-available/default
sudo sed -i -E "s/^server \{/$new_string2/" /etc/nginx/sites-available/default

# Start the Nginx service
sudo service nginx start
