#!/usr/bin/env bash
###############################################################################
# This Bash script installs and configures HAproxy in a load balancer server.
# It ensures that HAproxy is set up to distribute traffic to web-01 and web-02 using a round-robin algorithm.
# The script also makes HAproxy manageable via an init script.
#
# Requirements:
# - Install HAproxy version 1.8.
# - Configure HAproxy to balance requests between web-01 and web-02.
# - Use the roundrobin algorithm for load balancing.
# - Ensure that HAproxy can be managed via an init script.
# - Make sure that your servers are configured with the right hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02.
#   If not, follow the provided tutorial.
#
# Usage:
# - Run this script on a new Ubuntu machine to meet the task requirements.
#
# Example:
# $ ./1-install_load_balancer
###############################################################################

# Add HAproxy repository and install HAproxy version 1.8
sudo apt-get update
sudo apt-get install -y haproxy

# Backup the original HAproxy configuration
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original

# Create a new HAproxy configuration file
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend load_balancer
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 294840-web-01 100.25.46.228:80 check
    server 294840-web-02 54.236.222.22:80 check
EOF

# Start the HAproxy service
sudo systemctl restart haproxy
sudo systemctl enable haproxy

# Verify the HAProxy status
sudo systemctl status haproxy