#!/usr/bin/env bash

################################################################################
# Script Name: 3-show_your_bash_pid_made_easy
# Description: Displays the PID and process name of processes containing the word "bash".
#
# Requirements:
# - You cannot use ps
################################################################################

# Use pgrep with the -l option to list processes and their PIDs matching the name "bash"
pgrep bash -l
