#!/usr/bin/env bash
#8-beheaded_process
################################################################################
# Script Name: 8-beheaded_process
# Description: Kills the process 7-highlander.
################################################################################

pkill -f -SIGKILL 7-highlander
