#!/usr/bin/env bash
#manage_my_process
################################################################################
# Script Name: manage_my_process
# Description: Bash script that writes "I am alive!" to the file /tmp/my_process
# indefinitely.
#              Pauses for 2 seconds between each message.
################################################################################

# Indefinitely writes "I am alive!" to the file /tmp/my_process
# Pauses for 2 seconds between each message
while true; do
    sudo bash -c 'echo "I am alive!" >> /tmp/my_process'
    sleep 2
done
