#!/usr/bin/env bash
# Script Name: 100-read_and_cut
################################################################################
# Description:
#     Displays the username, user ID, and home directory path for each user
#     listed in the file /etc/passwd.
#
# Usage:
#     ./100-read_and_cut
################################################################################

# Read each line of the /etc/passwd file
while IFS= read -r line; do
    # Display the extracted information
    echo "$line" | cut -d ':' -f 1,3,6
done </etc/passwd
