#!/usr/bin/env bash
# Script Name: 101-tell_the_story_of_passwd
################################################################################
# Description:
#     Displays a story based on the content of the file /etc/passwd.
#
# Usage:
#     ./101-tell_the_story_of_passwd
################################################################################

# Set the Internal Field Separator (IFS) to ':'
IFS=":"

# Read each line of the /etc/passwd file
while read -r f1 f2 f3 f4 f5 f6 f7; do
    echo "The user $f1 is part of the $f4 gang, lives in $f6 and rides $f7. $f3's place is protected by the passcode $f2, more info about the user here: $f5"
done </etc/passwd

