#!/usr/bin/env bash
# Script Name: 103-dig_the-data
################################################################################
# Description:
#     Groups visitors by IP and HTTP status code and displays the data.
#
# Usage:
#     ./103-dig_the-data
################################################################################

awk '{ print $1,$9 }' apache-access.log | sort | uniq -c | sort -nr

