#!/usr/bin/env bash
# Script Name: 103-dig_the-data
################################################################################
# Description:
#     Groups visitors by IP and HTTP status code and displays the data.
#
# Usage:
#     ./103-dig_the-data
################################################################################

awk '{count[$1" "$9]++} END {for (key in count) print count[key], key}' apache-access.log | sort -nr
