#!/usr/bin/env bash
# Script Name: 6-superstitious_numbers
################################################################################
# Description:
#     Displays numbers from 1 to 20 and shows different messages for specific loop iterations.
#     - Displays "4" and "bad luck from China" for the 4th iteration.
#     - Displays "9" and "bad luck from Japan" for the 9th iteration.
#     - Displays "17" and "bad luck from Italy" for the 17th iteration.
#
# Usage:
#     ./6-superstitious_numbers
################################################################################

count=1

while [ $count -le 20 ]; do
    case $count in
    4)
        echo $count
        echo "bad luck from China"
        ;;
    9)
        echo $count
        echo "bad luck from Japan"
        ;;
    17)
        echo $count
        echo "bad luck from Italy"
        ;;
    *)
        echo $count
        ;;
    esac

    count=$((count + 1))
done
