#!/usr/bin/env bash
# Script Name: 9-to_file_or_not_to_file
################################################################################
# Description:
#     Checks if the "school" file exists and provides information about it.
#     Prints whether the file exists or not, if it is empty or not, and if it is
#     a regular file.
#
# Usage:
#     ./9-to_file_or_not_to_file
################################################################################

file="school"

# Check if the file exists
if [ -e "$file" ]; then
    echo "$file file exists"

    # Check if the file is empty
    if [ -s "$file" ]; then
        echo "$file file is not empty"
    else
        echo "$file file is empty"
    fi

    # Check if the file is a regular file
    if [ -f "$file" ]; then
        echo "$file is a regular file"
    fi
else
    echo "$file file does not exist"
fi
