#!/usr/bin/env bash
###############################################################################
# Script: 0-block_all_incoming_traffic_but.sh
#
# Description:
# This script installs & configures the ufw (Uncomplicated Firewall) - a server
# to block all incoming traffic except for SSH (port 22),
# HTTPS (port 443), and HTTP (port 80).
#
# Usage:
# - Make sure you have SSH access to the server.
# - Execute this script with sudo privileges.
#
# Example:
# sudo ./0-block_all_incoming_traffic_but.sh
#
# Author: Alexander Udeogaranya
# Date: September 18, 2023
###############################################################################

# Update package repositories and install ufw
sudo apt update
sudo apt install ufw -y

# Set default incoming policy to deny
sudo ufw default deny incoming

# Allow incoming traffic on SSH, HTTPS, and HTTP ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Enable the firewall
sudo ufw enable

# Display firewall status
sudo ufw status
