#!/usr/bin/env bash
# Script: 100-port_listening_on_localhost
###############################################################################
# Description: Listens on port 98 on localhost and displays incoming data
# Author: Alexander Udeogaranya
# Date: July 5, 2023
# Usage: ./100-port_listening_on_localhost
#
# Instructions:
# 1. Start the script by executing "./100-port_listening_on_localhost" in one terminal.
# 2. Open another terminal and connect to localhost on port 98 using the "telnet" command.
# 3. Type any text in the telnet session and press Enter.
# 4. The text will be displayed in the first terminal where the script is running.
#
# Note: This script is designed to run entirely within the localhost for demonstration purposes.
#
# Dependencies:
# - The script requires the `nc` (netcat) command to be installed and available on the system.
###############################################################################

# Listen on port 98 using netcat
nc -l 98

###############################################################################
# Comments:
# - This script uses the `nc` command to listen on port 98 on localhost.
# - It waits for incoming connections and displays any data received.
# - The `telnet` command can be used to establish a connection to the script and send data.
# - The script is useful for debugging socket connections, testing network connectivity,
#   and troubleshooting firewall rules.
# - Ensure that the `nc` command is installed on the system before running the script.
# - Customize the script as needed for your specific use case.
###############################################################################

