#!/usr/bin/env bash
# Configure Nginx to run as the 'nginx' user & listen on port 8080.

# Set a user in the config by replacing '#user' with 'user nginx'.
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# Update Nginx default site configuration to listen on port 8080.
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# Give owner permissions to read and write to the config file.
chmod 644 /etc/nginx/nginx.conf
# Stop Apache if it's running, as it may interfere with Nginx.
pkill apache2
# Start the Nginx service with the new 'nginx' user.
sudo -u nginx service nginx start
